### ISSUE TITLE
missing fontawesome script bundle

### ISSUE THREAD

**Issue by glebpigulevsky** [it-beard/itbeard-site#13]
![image](https://user-images.githubusercontent.com/56892495/195272170-7b201e39-12a5-44f6-b113-07ae41e0bf3b.png)
 this was ocurred in https://github.com/it-beard/itbeard-site/commit/1104acbd664adf484562eb44c9ed3e39ad0e1e50#diff-9ad4bdff9cc4bb9376c8d56900d12b411abe6636a78808c4793918b1e4c9680dL31

**Comment by glebpigulevsky** [comment]
https://github.com/it-beard/itbeard-site/pull/14 @itbeard

**Comment by itbeard** [comment]
дзяк!
