### ISSUE TITLE
Апісанне Instagram

### ISSUE THREAD

**Issue by balamyt** [it-beard/itbeard-site#2]
**Вы хацелі ішуя? Я дам вам ішуя!**

У раздзеле "Дадатковыя прывабнушкі" пра _instagram_ сярод іншага вы пішаце:
   `... backstage са здымак...`
на маю думку трэба
   `... backstage са здымакаў...`
   
   Проста прапушчаны канчатак.
   
<img width="426" alt="image" src="https://user-images.githubusercontent.com/7931633/191906826-db233c87-4c92-4177-8bbe-d8d64ecc8afb.png">

**Comment by glebpigulevsky** [comment]
@balamyt хм. тут патрэбна кансультацыя настаўніка, на маю думку ўсе правільна перекладзена. і наогул ```здымакаў``` неправільна пабудаванае слова

**Comment by itbeard** [comment]
> @balamyt хм. тут патрэбна кансультацыя настаўніка, на маю думку ўсе правільна перекладзена. і наогул `здымакаў` неправільна пабудаванае слова

У выніку вырашыў змяніць на "відарысы таго, што адбываецца па-за камерай"
