### ISSUE TITLE
Ў 

### ISSUE THREAD

**Issue by Maryia02** [it-beard/itbeard-site#3]
У запазычаных словах ў не пішацца (шоу на абодвух скрынах) 
![Screenshot_20220923_094433_com android chrome](https://user-images.githubusercontent.com/114214113/191907814-594dfaf5-1f04-485a-9593-5ecbf40d974f.jpg)
![Screenshot_20220923_094722_com android chrome](https://user-images.githubusercontent.com/114214113/191907837-f837f9d5-7e0a-4612-85f9-892a6f26fb14.jpg)
![Screenshot_20220923_100005_com android chrome](https://user-images.githubusercontent.com/114214113/191907856-21ce1059-8875-474f-9ff7-abc015ff1530.jpg)

**Comment by glebpigulevsky** [comment]
https://github.com/it-beard/itbeard-site/pull/9 @itbeard
