### ISSUE TITLE
Ад Naščadak VKL

### ISSUE THREAD

**Issue by itbeard** [it-beard/itbeard-site#6]
![image](https://user-images.githubusercontent.com/45439635/192064386-d95cb328-ff41-4fe2-a242-b3dd334fec49.png)

**Comment by glebpigulevsky** [comment]
https://github.com/it-beard/itbeard-site/pull/12 @itbeard

**Comment by itbeard** [comment]
> #12 @itbeard

- Выправіў на "існых" (падабаецца больш чым наркамаўскі варянт)
- Выправіў з "запісе Навін Барады" на "запісу Навінаў Барады"

Усім дзякуй!)
