### ISSUE TITLE
extra 'ў'

### ISSUE THREAD

**Issue by glebpigulevsky** [it-beard/itbeard-site#7]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/56892495/192134853-df6ae238-0411-4a32-b814-5149741f0a55.png">

you dont need 'ў' in the title

**Comment by glebpigulevsky** [comment]
https://github.com/it-beard/itbeard-site/pull/8 @itbeard

**Comment by itbeard** [comment]
Дзякуй!)
